### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-rpc-ri#57]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
Jobs:
- master: https://jenkins.eclipse.org/metro/job/jax-rpc-ri-master-build/
- EE4J_8: https://jenkins.eclipse.org/metro/job/jax-rpc-ri-ee4j8-build/

Build requires FastInfoset-1.0.2.jar to build. Later versions cause build to fail.
