### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-rpc-ri#58]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by Tomas-Kraus** [comment]
Job was created on https://jenkins.eclipse.org/metro/job/jax-rpc-ri-release/
Unfortunately this is not maven project so finishing this job will be more challenging.

**Comment by Tomas-Kraus** [comment]
Let's close this task now. Fixing release process can be covered by another issue.

**Comment by Tomas-Kraus** [comment]
Created Issue https://github.com/eclipse-ee4j/jax-rpc-ri/issues/64 to cover this.
