### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-rpc-ri#87]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by Tomas-Kraus** [comment]
Release job passed: https://jenkins.eclipse.org/metro/job/nexus-staging/42/console
PR to merge release info: https://github.com/eclipse-ee4j/jax-rpc-ri/pull/88
